using System.Collections.Generic;
using UnityEngine;

namespace NavigationFramework
{
    /// <summary>
    /// The geometry-based nearest-neighbor connection algorithm shared by the Editor's Auto Connect
    /// (<c>NavigationAutoConnector</c>, for authored <see cref="NavigationGraph"/> nodes) and
    /// runtime callers connecting dynamically spawned nodes (<see cref="NavigationManager.RegisterDynamicNode"/>)
    /// after a <c>LayoutGroup</c> has positioned them — e.g. an inventory list whose item count
    /// changes at runtime, where hand-authoring connections in the Graph Window isn't possible
    /// because the nodes don't exist until Play.
    /// </summary>
    public static class NavigationGeometryConnector
    {
        private static readonly Direction[] Directions = { Direction.Up, Direction.Down, Direction.Left, Direction.Right };

        /// <summary>
        /// For each node in <paramref name="nodes"/> with a <c>RectTransform</c>, connects it to
        /// the nearest other node in <paramref name="nodes"/> (also with a <c>RectTransform</c>) in
        /// each of the four directions, based on real world-space geometry. Nodes without a
        /// <c>RectTransform</c> are skipped entirely, both as a source and a candidate. Unlike the
        /// Editor's Auto Connect, this does not check Group/Page on its own — pass only the nodes
        /// that should be allowed to connect to each other (e.g. call once per Group/Page bucket)
        /// — and does not clear any existing connections first; call <see cref="DisconnectAll"/>
        /// before re-running on a list that changed, to avoid accumulating duplicate connections.
        /// </summary>
        /// <param name="nodes">The nodes to connect to each other.</param>
        /// <param name="markAutoGenerated">
        /// Whether to flag every created connection <see cref="NavigationConnection.IsAutoGenerated"/>.
        /// The Editor's Auto Connect sets this so a later re-run can regenerate only its own prior
        /// output; runtime dynamic-content callers typically leave it false since the flag has no
        /// special meaning for nodes that aren't part of a <see cref="NavigationGraph"/> asset.
        /// </param>
        public static int Connect(IReadOnlyList<NavigationNode> nodes, bool markAutoGenerated = false)
        {
            int created = 0;

            foreach (NavigationNode node in nodes)
            {
                if (node.RectTransform == null)
                {
                    continue;
                }

                Vector2 center = WorldCenter(node.RectTransform);

                foreach (Direction direction in Directions)
                {
                    NavigationNode nearest = FindNearestInDirection(nodes, node, center, direction);

                    if (nearest == null)
                    {
                        continue;
                    }

                    var connection = new NavigationConnection(nearest.Id, direction);

                    if (markAutoGenerated)
                    {
                        connection.SetAutoGenerated(true);
                    }

                    node.AddConnection(connection);
                    created++;
                }
            }

            return created;
        }

        /// <summary>
        /// Removes every connection from any node in <paramref name="nodes"/> whose target is also
        /// in <paramref name="nodes"/> — call before re-running <see cref="Connect"/> on a list
        /// that has been re-laid-out or changed, so old edges don't accumulate alongside new ones.
        /// Connections pointing outside <paramref name="nodes"/> (e.g. an authored "entry" node's
        /// link into this list) are left untouched.
        /// </summary>
        public static void DisconnectAll(IReadOnlyList<NavigationNode> nodes)
        {
            var nodeIds = new HashSet<string>();

            foreach (NavigationNode node in nodes)
            {
                nodeIds.Add(node.Id);
            }

            foreach (NavigationNode node in nodes)
            {
                List<NavigationConnection> toRemove = null;

                foreach (NavigationConnection connection in node.Connections)
                {
                    if (nodeIds.Contains(connection.TargetNodeId))
                    {
                        (toRemove ??= new List<NavigationConnection>()).Add(connection);
                    }
                }

                if (toRemove == null)
                {
                    continue;
                }

                foreach (NavigationConnection connection in toRemove)
                {
                    node.RemoveConnection(connection);
                }
            }
        }

        private static NavigationNode FindNearestInDirection(IReadOnlyList<NavigationNode> nodes, NavigationNode from, Vector2 fromCenter, Direction direction)
        {
            NavigationNode nearest = null;
            float nearestDistanceSqr = float.MaxValue;

            foreach (NavigationNode candidate in nodes)
            {
                if (candidate == from || candidate.RectTransform == null)
                {
                    continue;
                }

                Vector2 candidateCenter = WorldCenter(candidate.RectTransform);
                Vector2 delta = candidateCenter - fromCenter;

                if (!MatchesDirection(delta, direction))
                {
                    continue;
                }

                float distanceSqr = delta.sqrMagnitude;

                if (distanceSqr < nearestDistanceSqr)
                {
                    nearestDistanceSqr = distanceSqr;
                    nearest = candidate;
                }
            }

            return nearest;
        }

        private static bool MatchesDirection(Vector2 delta, Direction direction)
        {
            bool horizontalDominant = Mathf.Abs(delta.x) > Mathf.Abs(delta.y);

            switch (direction)
            {
                case Direction.Right: return horizontalDominant && delta.x > 0f;
                case Direction.Left: return horizontalDominant && delta.x < 0f;
                case Direction.Up: return !horizontalDominant && delta.y > 0f;
                case Direction.Down: return !horizontalDominant && delta.y < 0f;
                default: return false;
            }
        }

        private static Vector2 WorldCenter(RectTransform rectTransform)
        {
            Vector3 worldCenter = rectTransform.TransformPoint(rectTransform.rect.center);
            return new Vector2(worldCenter.x, worldCenter.y);
        }
    }
}
