using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

namespace NavigationFramework.Editor
{
    /// <summary>
    /// Generates <see cref="NavigationConnection"/>s between <see cref="NavigationNode"/>s based on
    /// the real screen geometry of their <see cref="NavigationNode.RectTransform"/>s, rather than
    /// requiring every edge to be drawn by hand in the Graph Window. Every connection it creates is
    /// marked <see cref="NavigationConnection.IsAutoGenerated"/> so a re-run (after moving widgets
    /// around) only replaces its own previous output — hand-drawn connections are never touched.
    /// </summary>
    public static class NavigationAutoConnector
    {
        private static readonly Direction[] Directions = { Direction.Up, Direction.Down, Direction.Left, Direction.Right };

        /// <summary>
        /// Removes every auto-generated connection in <paramref name="graph"/>, then regenerates
        /// one connection per direction per node — the nearest node whose <c>RectTransform</c>
        /// center lies in that direction, restricted to nodes sharing the same Group and Page
        /// (nodes with no <c>RectTransform</c> are skipped entirely, both as a source and a
        /// candidate, since there is no geometry to reason about).
        /// </summary>
        public static void AutoConnect(NavigationGraph graph)
        {
            if (graph == null)
            {
                return;
            }

            Undo.RecordObject(graph, "Auto Connect Navigation Graph");

            RemoveAutoGeneratedConnections(graph);

            int created = 0;

            foreach (NavigationNode node in graph.Nodes)
            {
                if (node.RectTransform == null)
                {
                    continue;
                }

                Vector2 center = WorldCenter(node.RectTransform);

                foreach (Direction direction in Directions)
                {
                    NavigationNode nearest = FindNearestInDirection(graph, node, center, direction);

                    if (nearest == null)
                    {
                        continue;
                    }

                    var connection = new NavigationConnection(nearest.Id, direction);
                    connection.SetAutoGenerated(true);
                    node.AddConnection(connection);
                    created++;
                }
            }

            NavigationGraphAutoSaver.Touch(graph);

            Debug.Log($"[NavigationFramework] Auto Connect on '{graph.name}': generated {created} connections.");
        }

        private static void RemoveAutoGeneratedConnections(NavigationGraph graph)
        {
            foreach (NavigationNode node in graph.Nodes)
            {
                List<NavigationConnection> toRemove = null;

                foreach (NavigationConnection connection in node.Connections)
                {
                    if (connection.IsAutoGenerated)
                    {
                        (toRemove ??= new List<NavigationConnection>()).Add(connection);
                    }
                }

                if (toRemove == null)
                {
                    continue;
                }

                foreach (NavigationConnection connection in toRemove)
                {
                    node.RemoveConnection(connection);
                }
            }
        }

        private static NavigationNode FindNearestInDirection(NavigationGraph graph, NavigationNode from, Vector2 fromCenter, Direction direction)
        {
            NavigationNode nearest = null;
            float nearestDistanceSqr = float.MaxValue;

            foreach (NavigationNode candidate in graph.Nodes)
            {
                if (candidate == from || candidate.RectTransform == null)
                {
                    continue;
                }

                if (!SameGroupAndPage(from, candidate))
                {
                    continue;
                }

                Vector2 candidateCenter = WorldCenter(candidate.RectTransform);
                Vector2 delta = candidateCenter - fromCenter;

                if (!MatchesDirection(delta, direction))
                {
                    continue;
                }

                float distanceSqr = delta.sqrMagnitude;

                if (distanceSqr < nearestDistanceSqr)
                {
                    nearestDistanceSqr = distanceSqr;
                    nearest = candidate;
                }
            }

            return nearest;
        }

        private static bool SameGroupAndPage(NavigationNode a, NavigationNode b)
        {
            return string.Equals(a.GroupId ?? string.Empty, b.GroupId ?? string.Empty) &&
                   string.Equals(a.PageId ?? string.Empty, b.PageId ?? string.Empty);
        }

        private static bool MatchesDirection(Vector2 delta, Direction direction)
        {
            bool horizontalDominant = Mathf.Abs(delta.x) > Mathf.Abs(delta.y);

            switch (direction)
            {
                case Direction.Right: return horizontalDominant && delta.x > 0f;
                case Direction.Left: return horizontalDominant && delta.x < 0f;
                case Direction.Up: return !horizontalDominant && delta.y > 0f;
                case Direction.Down: return !horizontalDominant && delta.y < 0f;
                default: return false;
            }
        }

        private static Vector2 WorldCenter(RectTransform rectTransform)
        {
            Vector3 worldCenter = rectTransform.TransformPoint(rectTransform.rect.center);
            return new Vector2(worldCenter.x, worldCenter.y);
        }
    }
}
