using System.Collections.Generic;
using System.Linq;
using UnityEditor;
using UnityEngine;

namespace NavigationFramework.Editor
{
    /// <summary>
    /// Generates <see cref="NavigationConnection"/>s between <see cref="NavigationNode"/>s based on
    /// the real screen geometry of their <see cref="NavigationNode.RectTransform"/>s, rather than
    /// requiring every edge to be drawn by hand in the Graph Window. Every connection it creates is
    /// marked <see cref="NavigationConnection.IsAutoGenerated"/> so a re-run (after moving widgets
    /// around) only replaces its own previous output — hand-drawn connections are never touched.
    /// The underlying nearest-neighbor algorithm lives in <see cref="NavigationGeometryConnector"/>
    /// (Runtime), shared with runtime callers connecting dynamically spawned content.
    /// </summary>
    public static class NavigationAutoConnector
    {
        /// <summary>
        /// Removes every auto-generated connection in <paramref name="graph"/>, then regenerates
        /// one connection per direction per node — the nearest node whose <c>RectTransform</c>
        /// center lies in that direction, restricted to nodes sharing the same Group and Page
        /// (nodes with no <c>RectTransform</c> are skipped entirely, both as a source and a
        /// candidate, since there is no geometry to reason about). Group/Page boundaries are
        /// enforced by running <see cref="NavigationGeometryConnector.Connect"/> once per
        /// (Group, Page) bucket, since that method only connects nodes within whatever list it's
        /// given to each other.
        /// </summary>
        public static void AutoConnect(NavigationGraph graph)
        {
            if (graph == null)
            {
                return;
            }

            Undo.RecordObject(graph, "Auto Connect Navigation Graph");

            RemoveAutoGeneratedConnections(graph);

            int created = 0;

            var buckets = graph.Nodes.GroupBy(node => (node.GroupId ?? string.Empty, node.PageId ?? string.Empty));

            foreach (var bucket in buckets)
            {
                created += NavigationGeometryConnector.Connect(bucket.ToList(), markAutoGenerated: true);
            }

            NavigationGraphAutoSaver.Touch(graph);

            Debug.Log($"[NavigationFramework] Auto Connect on '{graph.name}': generated {created} connections.");
        }

        private static void RemoveAutoGeneratedConnections(NavigationGraph graph)
        {
            foreach (NavigationNode node in graph.Nodes)
            {
                List<NavigationConnection> toRemove = null;

                foreach (NavigationConnection connection in node.Connections)
                {
                    if (connection.IsAutoGenerated)
                    {
                        (toRemove ??= new List<NavigationConnection>()).Add(connection);
                    }
                }

                if (toRemove == null)
                {
                    continue;
                }

                foreach (NavigationConnection connection in toRemove)
                {
                    node.RemoveConnection(connection);
                }
            }
        }
    }
}
